### ISSUE TITLE
Restart shoots bubble

### ISSUE THREAD

**Issue by defnoob** [peace-4-you/TI2206-2016-2017#115]
After clicking on restart, the cannon will occasionally shoot one immediately after restarting(~0.2s)

**Comment by mauricewillemsen** [comment]
That just happens when you fire quick a lot of bubbles before failing. Guess its 'stuck' in a kind of buffer. It isn't anything we can fix in the code. Just like with the statetransistions before drawing again, it's part of Slick2D
