### ISSUE TITLE
Sometimes some bubble get stuck

### ISSUE THREAD

**Issue by peace-4-you** [peace-4-you/TI2206-2016-2017#29]
When bubbles pop or drop, they sometimes don't disappear. They are "stuck"

**Comment by mauricewillemsen** [comment]
Found a cause. When bubble of the same color of the popped bubbles is in the to be dropped bubbles, he stays in the field. Maybe that helps

**Comment by peace-4-you** [comment]
This issue seems to be solved in the fixBubbleErrors branch
