### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by peace-4-you** [peace-4-you/TI2206-2016-2017#30]
In my __very limited__ knowledge it causes by getRow() and getColumn() calculations

**Comment by defnoob** [comment]
Game crashed just now when trying to drop bubbles. This crash seemed to be a getRow issue(crashed at get element from the linkedlist)

**Comment by defnoob** [comment]
Game crashes when there's a floating bubble left after dropping(at least I'm assuming only from dropping so far). Error is usually because the row that the floating bubble is in, doesn;t exist anymore.

**Comment by peace-4-you** [comment]
This issue seems to be solved in the fixBubbleErrors branch
