### ISSUE TITLE
Bubbles not landing in hexagonal grid

### ISSUE THREAD

**Issue by defnoob** [peace-4-you/TI2206-2016-2017#35]
Sometimes bubbles wont land in a hexagonal grid. Instead they will be placed slightly off and will force other bubbles that land on it in its own grid.

**Comment by defnoob** [comment]
There is also an issue with calculating the row and column for the bubble, but it is unknown where that goes wrong.

**Comment by peace-4-you** [comment]
This issue seems to be solved in the fixBubbleErrors branch
